# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/main_window.ui',
# licensing of 'views/main_window.ui' applies.
#
# Created: Thu Oct 24 14:42:57 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cmb_categories = QtWidgets.QComboBox(self.groupBox)
        self.cmb_categories.setObjectName("cmb_categories")
        self.gridLayout_2.addWidget(self.cmb_categories, 1, 0, 1, 1)
        self.lst_products = QtWidgets.QListView(self.groupBox)
        self.lst_products.setObjectName("lst_products")
        self.gridLayout_2.addWidget(self.lst_products, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 412))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_nutriments = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_nutriments.sizePolicy().hasHeightForWidth())
        self.lbl_nutriments.setSizePolicy(sizePolicy)
        self.lbl_nutriments.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbl_nutriments.setObjectName("lbl_nutriments")
        self.gridLayout_4.addWidget(self.lbl_nutriments, 10, 0, 1, 1)
        self.lbl_allergens = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_allergens.sizePolicy().hasHeightForWidth())
        self.lbl_allergens.setSizePolicy(sizePolicy)
        self.lbl_allergens.setWordWrap(True)
        self.lbl_allergens.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbl_allergens.setObjectName("lbl_allergens")
        self.gridLayout_4.addWidget(self.lbl_allergens, 5, 0, 1, 1)
        self.lbl_ingredients = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_ingredients.sizePolicy().hasHeightForWidth())
        self.lbl_ingredients.setSizePolicy(sizePolicy)
        self.lbl_ingredients.setWordWrap(True)
        self.lbl_ingredients.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbl_ingredients.setObjectName("lbl_ingredients")
        self.gridLayout_4.addWidget(self.lbl_ingredients, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 12, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 7, 0, 1, 1)
        self.lbl_palm_oil = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbl_palm_oil.setStyleSheet("* { background-color: red; color: white; padding: 3 px; }")
        self.lbl_palm_oil.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_palm_oil.setObjectName("lbl_palm_oil")
        self.gridLayout_4.addWidget(self.lbl_palm_oil, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.lbl_nutriscore = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbl_nutriscore.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_nutriscore.setObjectName("lbl_nutriscore")
        self.gridLayout_4.addWidget(self.lbl_nutriscore, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 2, 1)
        self.lbl_nutriscore_number = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbl_nutriscore_number.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_nutriscore_number.setObjectName("lbl_nutriscore_number")
        self.gridLayout_4.addWidget(self.lbl_nutriscore_number, 9, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_show_product = QtWidgets.QPushButton(self.tab_4)
        self.btn_show_product.setObjectName("btn_show_product")
        self.gridLayout_3.addWidget(self.btn_show_product, 2, 0, 1, 1)
        self.btn_find_substitutes = QtWidgets.QPushButton(self.tab_4)
        self.btn_find_substitutes.setObjectName("btn_find_substitutes")
        self.gridLayout_3.addWidget(self.btn_find_substitutes, 0, 0, 1, 2)
        self.btn_save_substitute = QtWidgets.QPushButton(self.tab_4)
        self.btn_save_substitute.setObjectName("btn_save_substitute")
        self.gridLayout_3.addWidget(self.btn_save_substitute, 2, 1, 1, 1)
        self.table_substitutes = QtWidgets.QTableView(self.tab_4)
        self.table_substitutes.setObjectName("table_substitutes")
        self.table_substitutes.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.table_substitutes, 1, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuOutils = QtWidgets.QMenu(self.menuBar)
        self.menuOutils.setObjectName("menuOutils")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_update = QtWidgets.QAction(MainWindow)
        self.action_update.setObjectName("action_update")
        self.action_preview = QtWidgets.QAction(MainWindow)
        self.action_preview.setObjectName("action_preview")
        self.menuOutils.addAction(self.action_update)
        self.menuOutils.addAction(self.action_preview)
        self.menuBar.addAction(self.menuOutils.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "NutriChecker by @RoroTiti", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Produits", None, -1))
        self.lbl_nutriments.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.lbl_allergens.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.lbl_ingredients.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Valeurs nutritionnelles pour 100g</b>", None, -1))
        self.lbl_palm_oil.setText(QtWidgets.QApplication.translate("MainWindow", "Contient de l\'huile de palme", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Ingrédients</b>", None, -1))
        self.lbl_nutriscore.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Allergènes</b>", None, -1))
        self.lbl_nutriscore_number.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Description", None, -1))
        self.btn_show_product.setText(QtWidgets.QApplication.translate("MainWindow", "Afficher le produit", None, -1))
        self.btn_find_substitutes.setText(QtWidgets.QApplication.translate("MainWindow", "Obtenir la liste des substituts", None, -1))
        self.btn_save_substitute.setText(QtWidgets.QApplication.translate("MainWindow", "Enregistrer dans les favoris", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "Substituts", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Nouvelle recherche", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Mon historique de recherche", None, -1))
        self.menuOutils.setTitle(QtWidgets.QApplication.translate("MainWindow", "Outils", None, -1))
        self.action_update.setText(QtWidgets.QApplication.translate("MainWindow", "Mise à jour des données...", None, -1))
        self.action_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Aperçu des données...", None, -1))

